system_prompts:
  Empty: '

    '
  think_tags: 'A conversation between User and Assistant. The user asks a question,
    and the Assistant solves it. The assistant first thinks about the reasoning process
    in the mind and then provides the user with the answer. The reasoning process
    and answer are enclosed within <think> </think> and <answer> </answer> tags, respectively,
    i.e., <think> reasoning process here </think><answer> answer here </answer>.

    '
user_prompts:
  detect_from_user: 'Please detect {USER_PROMPT} in the image.

    '
